// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Health_Care_Web_API.Data.Configuration;
using Health_Care_Web_API.Models;
using Microsoft.EntityFrameworkCore;

namespace Health_Care_Web_API.Data;

public partial class HEALTH_CARE_SYSTEM_DBContext : DbContext
{
    public HEALTH_CARE_SYSTEM_DBContext()
    {
    }

    public HEALTH_CARE_SYSTEM_DBContext(DbContextOptions<HEALTH_CARE_SYSTEM_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<Doctor> Doctors { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Name=DefaultConnection");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);


        modelBuilder.ApplyConfigurationsFromAssembly(typeof(HEALTH_CARE_SYSTEM_DBContext).Assembly);
        modelBuilder.Entity<Appointment>().HasQueryFilter(a => !a.IsDeleted);
        modelBuilder.Entity<Doctor>().HasQueryFilter(d => !d.IsDeleted);
        modelBuilder.Entity<Patient>().HasQueryFilter(p => !p.IsDeleted);
    }

    //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}